#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

DIR="/data/pac/init";
LOG="$DIR/tweaks.log";
CFG="$DIR/init.cfg";
SCP="/system/etc/helpers.sh";

. $SCP;

# Fix Permissions
busybox chmod 644 $CFG;
busybox chmod 644 $SCP;

# Check if the folder exists
if [ ! -d $DIR ]; then
    mkdir $DIR;
fi;

# Check if the file exists
if [ -f $LOG ]; then
    rm $LOG;
fi;

# Fisrt Boot
for x in "/system/xbin" "/data"; do
    if [ -f ${x}/firstboot.sh ]; then
        sh ${x}/firstboot.sh;
        rm -f ${x}/firstboot.sh;
    fi;
done;

if [ ! -f $CFG ]; then
    cat >> $CFG << EOF
# ================ Copyright (C) 2014 PAC-Roms Project ================
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# =====================================================================

# Libraries
paclog="/data/pac/init/tweaks.log"
aheadfile="/sys/devices/virtual/bdi/179:0/read_ahead_kb"
SCP="/system/etc/helpers.sh"
sysctl_conf="/system/etc/sysctl.conf"


# MISC
STL=`ls -d /sys/block/stl*`
BML=`ls -d /sys/block/bml*`
MMC=`ls -d /sys/block/mmc*`
MEM=`busybox free|grep Mem | awk '{print $2}'`
SQL=`busybox find /d* -iname "*.db"`
TSC="/sys/class/touch/switch/set_touchscreen"
KERNEL="/sys/kernel/debug/sched_features"


# Booleans
zipalign=false
permissions=false
sysctl=false
cache=false
cron=false
filesystem=false
battery=false
touch=false
gpurender=false
sleepers=false
journalism=false
sqlite3=false
wifisleep=false
iostats=false
sdboost=false
ahead=2048
setrenice=false
kernel=false
vm=false
net=false

EOF
fi;

echo "PACman ROM Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )\n\n" | tee -a $LOG;
