#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

PACDIR="/data/local"
LOGDIR="$PACDIR/PACLogs"
LOG="$LOGDIR/tweaks.log"
CFG="$PACDIR/init.d.cfg

busybox mount -o rw,remount /system;

# Fix Permission of cfg_file on boot
busybox chmod -urwx -grw -or $cfg;

# Check if the folder exists
if [ ! -d $LOGDIR ]; then
    mkdir $LOGDIR
fi

# Note: this is the *only* write to the tweaks log that does not append (overwrites)!
echo "PACman ROM Tweaks Check Starting At $( date +"%m-%d-%Y %H:%M:%S" )\n\n" | tee $LOG

# First Boot
for x in "/system/xbin" "/data"; do
    if [ -f ${x}/firstboot.sh ]; then
        sh ${x}/firstboot.sh
        rm -f ${x}/firstboot.sh
    fi
done

if [ ! -f $CFG ]; then
    cat >> $CFG << EOF
# ================ Copyright (C) 2014 PAC-Roms Project ================
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# =====================================================================

# Libraries
LOGDIR="$LOGDIR"
PACLOG="\$LOGDIR/tweaks.log"
sysctlfile="/system/etc/sysctl.conf"


# Misc
AHF="/sys/devices/virtual/bdi/179:0/read_ahead_kb"
MIN="/sys/module/lowmemorykiller/parameters/minfree"
TSC="/sys/class/touch/switch/set_touchscreen"
KERNEL="/sys/kernel/debug/sched_features"


# Booleans
zipalign=false
sysctl=false
setrenice=false
filesystem=false
freemem=false
cache=false
permissions=false
kernel=false
cron=false
sdboost=false
ahead=2048
battery=false
touch=false
vm=false
net=false
sleepers=false
journalism=false
sqlite=false
wifisleep=false
iostats=false


# Memory Thresholds
foreground_app_mem=2048
visible_app_mem=4096
perceptible_app_mem=4096
heavy_weight_app_mem=4096
secondary_server_mem=8192
backup_app_mem=8192
home_app_mem=8192
hidden_app_mem=12288
empty_app_mem=16384

EOF
fi

busybox mount -o ro,remount /system;

echo "PACman ROM Tweaks Check Finished At $( date +"%m-%d-%Y %H:%M:%S" )\n\n" | tee -a $LOG
