#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/pac/init.cfg
LOG="/data/pac/zipalign.log"

if $zipalign; then
    if [ -e $LOG ]; then
        rm $LOG;
    fi;
    echo "Starting Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG;
    for apk in /data/app/*.apk ; do
        /system/xbin/zipalign -c 4 $apk;
        ZIPCHECK=$?;
        if [ $ZIPCHECK -eq 1 ]; then
            echo ZipAligning $(basename $apk)  | tee -a $LOG;
            /system/xbin/zipalign -f 4 $apk /cache/$(basename $apk);
            if [ -e /cache/$(basename $apk) ]; then
                cp -f -p /cache/$(basename $apk) $apk  | tee -a $LOG;
                rm /cache/$(basename $apk);
            else
                echo ZipAligning $(basename $apk) Failed  | tee -a $LOG;
            fi;
        else
            echo ZipAlign already completed on $apk  | tee -a $LOG;
        fi;
    done;
    echo "Finished Automatic ZipAlign at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG;
    echo "* ZipAlign Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $paclog;
fi;
