#!/system/bin/sh
: '
 ========= Copyright (C) 2014 The PAC-man Team (The AIO Rom) =========

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/local/init.d.cfg

if $setrenice; then
    renice -20 `pidof com.android.phone`;
    renice -19 `pidof com.android.inputmethod.latin`;
    renice -17 `pidof com.android.systemui`;
    renice -15 `pidof com.android.launcher3`;
    renice -9 `pidof com.android.settings`;
    renice -9 `pidof com.android.vending`;
    renice -6 `pidof com.google.android.apps.maps`;
    renice -4 `pidof com.google.android.apps.googlevoice`;
    renice -3 `pidof android.process.media`;
    echo "* Sentrenice Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $paclog;
fi;
