#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/local/init.d.cfg

if $clear_data_cache; then
    busybox find /data/data -type d -iname "*cache*" -maxdepth 2 -mindepth 2 -exec busybox rm -rf {} ';';
    busybox rm -f /data/anr/*.*;
    busybox rm -f /data/cache/*.*;
    busybox rm -f /data/log/*.*;
    busybox rm -f /data/mlog/*;
    busybox rm -f /data/tombstones/*;
    busybox rm -f /data/backup/pending/*;
    busybox rm -r /data/local/tmp/*;
    busybox rm -r /data/system/appusagestats/*;
    busybox rm -r /data/system/dropbox/*;
    busybox rm -f /data/system/usagestats/*;
    busybox chmod 700 /data/system/dropbox;
    busybox chmod 700 /data/system/usagestats;
    echo "* RemoveCache Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $paclog;
fi;
