#!/system/bin/sh
#
. /system/etc/init.d.cfg

if $battery; then
	echo "1000" > /proc/sys/vm/dirty_expire_centisecs;
	echo "2000" > /proc/sys/vm/dirty_writeback_centisecs;
	echo "Baterry Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a /data/PACLogs/tweaks.log;
fi
