#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/local/init.d.cfg

if $touch; then
    if [ -e $TSC ]; then
        echo "7025" >> $TSC;
        echo "8002" >> $TSC;
        echo "11001" >> $TSC;
        echo "13030" >> $TSC;
        echo "14005" >> $TSC;
        echo "* Touch Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $paclog;
    else
        echo "* ERROR - Touch Tweaks is not supported by your device, we are sorry" | tee -a $paclog;
    fi;
fi;
