#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/local/init.d.cfg
MEM=`busybox free|grep Mem | awk '{print $2}'`

if $vm; then
    echo "* Virtual Machine Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PACLOG

    echo "0" > /proc/sys/vm/laptop_mode
    echo "0" > /proc/sys/vm/mmap_min_addr
    echo "0" > /proc/sys/vm/oom_kill_allocating_task
    echo "0" > /proc/sys/vm/panic_on_oom
    echo "0" > /proc/sys/vm/scan_unevictable_pages
    echo "0" > /proc/sys/vm/swappiness
    echo "0" > /proc/sys/vm/block_dump
    echo "1" > /proc/sys/vm/highmem_is_dirtyable
    echo "1" > /proc/sys/vm/stat_interval
    echo "1" > /proc/sys/vm/oom_dump_tasks
    echo "10" > /proc/sys/vm/vfs_cache_pressure
    echo "1000" > /proc/sys/vm/dirty_expire_centisecs
    echo "2000" > /proc/sys/vm/dirty_writeback_centisecs
    echo "3" > /proc/sys/vm/drop_caches
    echo "4096" > /proc/sys/vm/min_free_kbytes
    echo "5" > /proc/sys/vm/min_free_order_shift
    echo "8" > /proc/sys/vm/page-cluster

    if [ "$MEM" -lt 512000 ]; then
       echo "15" > /proc/sys/vm/dirty_background_ratio
       echo "30" > /proc/sys/vm/dirty_ratio
    elif [ "$MEM" -lt 1024000 ]; then
       echo "10" > /proc/sys/vm/dirty_background_ratio
       echo "20" > /proc/sys/vm/dirty_ratio
    else
       echo "5" > /proc/sys/vm/dirty_background_ratio
       echo "10" > /proc/sys/vm/dirty_ratio
    fi

    echo "* Virtual Machine Tweaks Finished At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PACLOG
fi
