#!/system/bin/sh
#
. /system/etc/init.d.cfg

if $gpurender; then
	sysrw;
	rm /system/lib/egl/libGLES_android.so;
	busybox sed -i '/0 0 android/d' /system/lib/egl/egl.cfg;
	sysro;
	echo "GPU Render Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a /data/PACLogs/tweaks.log;
fi
