#!/system/bin/sh
#
. /system/etc/init.d.cfg

if $sleepers; then
	mount -t debugfs none /sys/kernel/debug;
	echo "NO_ARCH_POWER" > /sys/kernel/debug/sched_features;
	echo "NO_GENTLE_FAIR_SLEEPERS" > /sys/kernel/debug/sched_features;
	echo "NO_NORMALIZED_SLEEPERS" > /sys/kernel/debug/sched_features;
	echo "NO_NEW_FAIR_SLEEPERS" > /sys/kernel/debug/sched_features;
	umount /sys/kernel/debug;
	echo "Sleepers Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a /data/PACLogs/tweaks.log;
fi
