#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/local/init.d.cfg

if $sleepers; then
    busybox mount -t debugfs none /sys/kernel/debug;
    if [ -e $KERNEL ]; then
        echo "NO_AFFINE_WAKEUPS" >> $KERNEL;
        echo "NO_ARCH_POWER" >> $KERNEL;
        echo "NO_CACHE_HOT_BUDDY" >> $KERNEL;
        echo "NO_DOUBLE_TICK" >> $KERNEL;
        echo "NO_FORCE_SD_OVERLAP" >> $KERNEL;
        echo "NO_GENTLE_FAIR_SLEEPERS" >> $KERNEL;
        echo "NO_HRTICK" >> $KERNEL;
        echo "NO_LAST_BUDDY" >> $KERNEL;
        echo "NO_LB_BIAS" >> $KERNEL;
        echo "NO_LB_MIN" >> $KERNEL;
        echo "NO_NEW_FAIR_SLEEPERS" >> $KERNEL;
        echo "NO_NEXT_BUDDY" >> $KERNEL;
        echo "NO_NONTASK_POWER" >> $KERNEL;
        echo "NO_NORMALIZED_SLEEPERS" >> $KERNEL;
        echo "NO_OWNER_SPIN" >> $KERNEL;
        echo "NO_RT_RUNTIME_SHARE" >> $KERNEL;
        echo "NO_START_DEBIT" >> $KERNEL;
        echo "NO_TTWU_QUEUE" >> $KERNEL;
        echo "* Sleepers Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $paclog;
    else
        echo "* ERROR - Sleepers Tweaks is not supported by your device, we are sorry" | tee -a $paclog;
    fi;
    busybox umount /sys/kernel/debug;
fi;
