#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/pac/init/init.cfg

if $iostats; then
    for X in $STL $BML $MMC; do
        busybox chmod 644 ${X}/queue/*;
        echo "0" >> ${X}/queue/iostats;
        echo "0" >> ${X}/queue/rotational;
        echo "1" >> ${X}/queue/iosched/back_seek_penalty;
        echo "1" >> ${X}/queue/iosched/fifo_batch;
        echo "1" >> ${X}/queue/iosched/low_latency;
        echo "1" >> ${X}/queue/iosched/writes_starved;
        echo "3" >> ${X}/queue/iosched/slice_idle;
        echo "16" >> ${X}/queue/iosched/quantum;
        echo "8192" >> ${X}/queue/nr_requests;
        echo "* IO Stats Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $paclog;
    done;
fi;
