#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/local/init.d.cfg
LOG="$LOGDIR/filesystem.log"

if $filesystem; then
    echo "* Ext4 Tweaks Finished At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PACLOG

    echo " Ext4 Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee $LOG
    echo " --- Remounting partitions with optimized options ..." | tee -a $LOG
    busybox mount -o remount,noatime,barrier=0,nodiratime /dev
    busybox mount -o remount,noatime,barrier=0,nodiratime /proc
    busybox mount -o remount,noatime,barrier=0,nodiratime /sys
    busybox mount -o remount,noatime,barrier=0,nodiratime /system
    busybox mount -o remount,noatime,barrier=0,nodiratime,noauto_da_alloc,nodev,nobh,rw,data=writeback /data
    busybox mount -o remount,noatime,barrier=0,nodiratime,noauto_da_alloc,nodev,nobh,rw,data=writeback /cache
    echo " --- Running fstrim ..." | tee -a $LOG
    busybox fstrim -v /cache | tee -a $LOG
    busybox fstrim -v /data | tee -a $LOG
    busybox fstrim -v /system | tee -a $LOG
    echo " Ext4 Tweaks Finished At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG

    echo "* Ext4 Tweaks Finished At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PACLOG
fi
