#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/local/init.d.cfg
LOG="$LOGDIR/fixperm.log"

if $permissions; then
    echo "* Fix Permisions Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PACLOG

    echo "Fix Permission started at $( date +"%m-%d-%Y %H:%M:%S" )" | tee $LOG
    for file in /data/app/*; do
        echo "Setting permissions (644) for $file" | tee -a $LOG
        chmod 644 $file
    done
    echo "Fix Permission finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG

    echo "* Fix Permisions Tweaks Finished At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PACLOG
fi
