#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/local/init.d.cfg

if $freemem; then
    echo "* Freemen Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PACLOG

    if [ -e $MIN ]; then
        echo $foreground_app_mem,$visible_app_mem,$perceptible_app_mem,$secondary_server_mem,$hidden_app_mem,$empty_app_mem >> $MIN
        setprop ro.FOREGROUND_APP_MEM $foreground_app_mem
        setprop ro.VISIBLE_APP_MEM $visible_app_mem
        setprop ro.PERCEPTIBLE_APP_MEM $perceptible_app_mem
        setprop ro.HEAVY_WEIGHT_APP_MEM $heavy_weight_app_mem
        setprop ro.SECONDARY_SERVER_MEM $secondary_server_mem
        setprop ro.BACKUP_APP_MEM $backup_app_mem
        setprop ro.HOME_APP_MEM $home_app_mem
        setprop ro.HIDDEN_APP_MEM $hidden_app_mem
        setprop ro.EMPTY_APP_MEM $empty_app_mem
    else
        echo " ** ERROR - Freemen Tweaks is not supported by your device, we are sorry." | tee -a $PACLOG
    fi

    echo "* Freemen Tweaks Finished At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PACLOG
fi
