#!/system/bin/sh
: '
 ================ Copyright (C) 2014 PAC-Roms Project ================

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 =====================================================================
'

. /data/local/init.d.cfg

if $kernel; then
    echo "* VM & Kernel Tweaks Starting At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PACLOG

    chown 0.0 /sys/kernel/mm/ksm/pages_to_scan
    chmod 664 /sys/kernel/mm/ksm/pages_to_scan
    chown 0.0 /sys/kernel/mm/ksm/sleep_millisecs
    chmod 664 /sys/kernel/mm/ksm/sleep_millisecs
    chown 0.0 /sys/kernel/mm/ksm/run
    chmod 664 /sys/kernel/mm/ksm/run
    echo "0" > /proc/sys/kernel/hung_task_timeout_secs
    echo "0" > /proc/sys/kernel/panic
    echo "0" > /proc/sys/kernel/panic_on_oops
    echo "0" > /proc/sys/kernel/sched_child_runs_first
    echo "0" > /proc/sys/kernel/softlockup_panic
    echo "1" > /sys/kernel/mm/ksm/run
    echo "1" > /proc/sys/kernel/sched_compat_yield
    echo "100000" > /proc/sys/kernel/sched_wakeup_granularity_ns
    echo "128" > /proc/sys/kernel/kernel/random/read_wakeup_threshold
    echo "12800" > /sys/kernel/mm/ksm/pages_to_scan
    echo "15000" > /sys/kernel/mm/ksm/sleep_millisecs
    echo "15834233" > /proc/sys/kernel/sched_features
    echo "18000000" > /proc/sys/kernel/sched_latency_ns
    echo "200000" > /proc/sys/kernel/sched_min_granularity_ns
    echo "256" > /proc/sys/kernel/kernel/random/write_wakeup_threshold
    echo "256000" > /proc/sys/kernel/sched_shares_ratelimit
    echo "400000" > /proc/sys/kernel/sched_latency_ns
    echo "524288" > /proc/sys/kernel/threads-max
    echo "64000" > /proc/sys/kernel/msgmni
    echo "65000" > /proc/sys/kernel/msgmax

    echo "* VM & Kernel Tweaks Finished At $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $PACLOG
fi
