# Nexus Q
add_lunch_combo pac_steelhead-userdebug
# Oppo 2013
add_lunch_combo pac_find5-userdebug
# Xperia 2013
##Board: Rhine
add_lunch_combo pac_honami-userdebug
##Board: Fusion3
add_lunch_combo pac_yuga-userdebug
add_lunch_combo pac_odin-userdebug
add_lunch_combo pac_pollux_windy-userdebug
add_lunch_combo pac_pollux-userdebug
# Xperia 2012
##Board: Blue
add_lunch_combo pac_mint-userdebug
add_lunch_combo pac_hayabusa-userdebug
add_lunch_combo pac_tsubasa-userdebug
##Board: Montblanc
add_lunch_combo pac_kumquat-userdebug
add_lunch_combo pac_lotus-userdebug
add_lunch_combo pac_nypon-userdebug
add_lunch_combo pac_pepper-userdebug
# Xperia 2011
##Board: Mogami
add_lunch_combo pac_anzu-userdebug
add_lunch_combo pac_coconut-userdebug
add_lunch_combo pac_haida-userdebug
add_lunch_combo pac_hallon-userdebug
add_lunch_combo pac_iyokan-userdebug
add_lunch_combo pac_mango-userdebug
add_lunch_combo pac_satsuma-userdebug
add_lunch_combo pac_smultron-userdebug
add_lunch_combo pac_urushi-userdebug
##Board: Zeus
add_lunch_combo pac_zeus-userdebug
# Samsung 2011
add_lunch_combo pac_captivatemtd-userdebug
add_lunch_combo pac_fascinatemtd-userdebug
add_lunch_combo pac_galaxysmtd-userdebug
add_lunch_combo pac_galaxysl-userdebug
add_lunch_combo pac_i777-userdebug
add_lunch_combo pac_i9100-userdebug
add_lunch_combo pac_i9103-userdebug
add_lunch_combo pac_i9100g-userdebug
add_lunch_combo pac_i927-userdebug
add_lunch_combo pac_d710-userdebug
add_lunch_combo pac_p1-userdebug
add_lunch_combo pac_p5-userdebug
add_lunch_combo pac_p5wifi-userdebug
# Samsung 2012
add_lunch_combo pac_exhilarate-userdebug
add_lunch_combo pac_hercules-userdebug
add_lunch_combo pac_skyrocket-userdebug
add_lunch_combo pac_t769-userdebug
add_lunch_combo pac_p5100-userdebug
add_lunch_combo pac_p5110-userdebug
add_lunch_combo pac_p3100-userdebug
add_lunch_combo pac_p3110-userdebug
# Nexus Devices
add_lunch_combo pac_crespo-userdebug
add_lunch_combo pac_flo-userdebug
add_lunch_combo pac_grouper-userdebug
add_lunch_combo pac_maguro-userdebug
add_lunch_combo pac_mako-userdebug
add_lunch_combo pac_manta-userdebug
add_lunch_combo pac_tilapia-userdebug
add_lunch_combo pac_toro-userdebug
add_lunch_combo pac_toroplus-userdebug
# HTC Rezound
add_lunch_combo pac_vigor-userdebug
# HTC Shooter
add_lunch_combo pac_shooter-userdebug
add_lunch_combo pac_shootervm-userdebug
add_lunch_combo pac_shooteru-userdebug
# HTC 2011
add_lunch_combo pac_ace-userdebug
add_lunch_combo pac_saga-userdebug
add_lunch_combo pac_vivo-userdebug
add_lunch_combo pac_runnymede-userdebug
# HTC 2013
add_lunch_combo pac_fireball-userdebug
add_lunch_combo pac_jewel-userdebug
add_lunch_combo pac_dlx-userbebug
add_lunch_combo pac_endeavoru-userdebug
add_lunch_combo pac_enrc2b-userdebug
add_lunch_combo pac_evita-userdebug
add_lunch_combo pac_ville-userdebug
add_lunch_combo pac_m7ul-userdebug
add_lunch_combo pac_m7att-userdebug
add_lunch_combo pac_m7tmo-userdebug
add_lunch_combo pac_m7spr-userdebug
add_lunch_combo pac_m7vzw-userdebug
# Samsung 2010
add_lunch_combo pac_epicmtd-userdebug
# Samsung 2013
add_lunch_combo pac_codinaMetroPCS-userdebug
add_lunch_combo pac_codinavid-userdebug
add_lunch_combo pac_codinatmo-userdebug
add_lunch_combo pac_d2att-userdebug
add_lunch_combo pac_d2cri-userdebug
add_lunch_combo pac_d2mtr-userdebug
add_lunch_combo pac_d2spr-userdebug
add_lunch_combo pac_d2tmo-userdebug
add_lunch_combo pac_d2usc-userdebug
add_lunch_combo pac_d2vzw-userdebug
add_lunch_combo pac_i605-userdebug
add_lunch_combo pac_i9300-userdebug
add_lunch_combo pac_i9305-userdebug
add_lunch_combo pac_i9500-userdebug
add_lunch_combo pac_jflteatt-userdebug
add_lunch_combo pac_jfltecan-userdebug
add_lunch_combo pac_jfltecri-userdebug
add_lunch_combo pac_jfltecsp-userdebug
add_lunch_combo pac_jfltespr-userdebug
add_lunch_combo pac_jfltetmo-userdebug
add_lunch_combo pac_jflteusc-userdebug
add_lunch_combo pac_jfltevzw-userdebug
add_lunch_combo pac_jfltexx-userdebug
add_lunch_combo pac_l900-userdebug
add_lunch_combo pac_r950-userdebug
add_lunch_combo pac_t0lte-userdebug
add_lunch_combo pac_t0lteatt-userdebug
add_lunch_combo pac_t0ltetmo-userdebug
add_lunch_combo pac_n5110-userdebug
add_lunch_combo pac_n7000-userdebug
add_lunch_combo pac_n7100-userdebug
add_lunch_combo pac_n8000-userdebug
add_lunch_combo pac_n8013-userdebug
add_lunch_combo pac_quincyatt-userdebug
add_lunch_combo pac_quincytmo-userdebug
add_lunch_combo pac_venturi-userdebug
add_lunch_combo pac_ypg1-userdebug
# Samsung & LGE Legacy Devices
add_lunch_combo pac_ancora-userdebug
add_lunch_combo pac_ariesve-userdebug
add_lunch_combo pac_gio-userdebug
add_lunch_combo pac_cooper-userdebug
add_lunch_combo pac_p500-userdebug
add_lunch_combo pac_tass-userdebug
add_lunch_combo pac_beni-userdebug
add_lunch_combo pac_p990-userdebug
add_lunch_combo pac_p920-userdebug
add_lunch_combo pac_p970-userdebug
# HTC One V
add_lunch_combo pac_primoc-userdebug
add_lunch_combo pac_primou-userdebug
# LGE
add_lunch_combo pac_e975-userdebug
add_lunch_combo pac_ls970-userdebug
add_lunch_combo pac_p760-userdebug
add_lunch_combo pac_p880-userdebug
add_lunch_combo pac_p930-userdebug
add_lunch_combo pac_su640-userdebug
add_lunch_combo pac_vs920-userdebug
# Motorola 2013
add_lunch_combo pac_edison-userdebug
add_lunch_combo pac_mb886-userdebug
add_lunch_combo pac_vanquish-userdebug
add_lunch_combo pac_spyder-userdebug
add_lunch_combo pac_targa-userdebug
add_lunch_combo pac_maserati-userdebug
add_lunch_combo pac_umts_spyder-userdebug
add_lunch_combo pac_solana-userdebug
add_lunch_combo pac_vanquishgsm-userdebug
add_lunch_combo pac_scorpionmini-userdebug
add_lunch_combo pac_xt897-userdebug
add_lunch_combo pac_xt897c-userdebug
# Asus device
add_lunch_combo pac_tf300t-userdebug
add_lunch_combo pac_tf201-userdebug
add_lunch_combo pac_tf700t-userdebug
# Amazon
add_lunch_combo pac_otter-userdebug
add_lunch_combo pac_otter2-userdebug
add_lunch_combo pac_tate-userdebug
add_lunch_combo pac_jem-userdebug
# HTC-legacy
add_lunch_combo pac_marvel-userdebug
add_lunch_combo pac_villec2-userdebug
add_lunch_combo pac_pico-userdebug
# Huawei
add_lunch_combo pac_u8860-userdebug
add_lunch_combo pac_u8800pro-userdebug
# ZTE
add_lunch_combo pac_atlas40-userdebug
