# Xperia 2013
add_lunch_combo pac_yuga-userdebug
add_lunch_combo pac_odin-userdebug
# Xperia 2011
add_lunch_combo pac_anzu-userdebug
add_lunch_combo pac_mango-userdebug
add_lunch_combo pac_smultron-userdebug
add_lunch_combo pac_coconut-userdebug
add_lunch_combo pac_satsuma-userdebug
add_lunch_combo pac_urushi-userdebug
add_lunch_combo pac_haida-userdebug
add_lunch_combo pac_zeus-userdebug
# Samsung 2011
add_lunch_combo pac_captivatemtd-userdebug
add_lunch_combo pac_fascinatemtd-userdebug
add_lunch_combo pac_galaxysmtd-userdebug
add_lunch_combo pac_i9100-userdebug
add_lunch_combo pac_i9103-userdebug
add_lunch_combo pac_i9100g-userdebug
add_lunch_combo pac_d710-userdebug
add_lunch_combo pac_p1-userdebug
# Samsung 2012
add_lunch_combo pac_hercules-userdebug
add_lunch_combo pac_skyrocket-userdebug
add_lunch_combo pac_p5100-userdebug
add_lunch_combo pac_p5110-userdebug
add_lunch_combo pac_p3100-userdebug
add_lunch_combo pac_p3110-userdebug
# Nexus Devices
add_lunch_combo pac_toro-userdebug
add_lunch_combo pac_mako-userdebug
add_lunch_combo pac_maguro-userdebug
add_lunch_combo pac_manta-userdebug
add_lunch_combo pac_crespo-userdebug
add_lunch_combo pac_grouper-userdebug
add_lunch_combo pac_tilapia-userdebug
# HTC Rezound
add_lunch_combo pac_vigor-userdebug
# HTC Shooter
add_lunch_combo pac_shooter-userdebug
add_lunch_combo pac_shootervm-userdebug
add_lunch_combo pac_shooteru-userdebug
# HTC 2011
add_lunch_combo pac_ace-userdebug
add_lunch_combo pac_saga-userdebug
# HTC 2013
add_lunch_combo pac_jewel-userdebug
add_lunch_combo pac_evita-userdebug
add_lunch_combo pac_ville-userdebug
#Samsung 2010
add_lunch_combo pac_epicmtd-userdebug
# Samsung 2013
add_lunch_combo pac_d2spr-userdebug
add_lunch_combo pac_d2tmo-userdebug
add_lunch_combo pac_d2att-userdebug
add_lunch_combo pac_d2vzw-userdebug
add_lunch_combo pac_i605-userdebug
add_lunch_combo pac_i9300-userdebug
add_lunch_combo pac_l900-userdebug
add_lunch_combo pac_t0lte-userdebug
add_lunch_combo pac_n7000-userdebug
add_lunch_combo pac_n7100-userdebug
add_lunch_combo pac_venturi_usa-userdebug
# Samsung & LGE Legacy Devices
add_lunch_combo pac_gio-userdebug
add_lunch_combo pac_cooper-userdebug
add_lunch_combo pac_p500-userdebug
add_lunch_combo pac_tass-userdebug
add_lunch_combo pac_beni-userdebug
add_lunch_combo pac_p990-userdebug
add_lunch_combo pac_p920-userdebug
add_lunch_combo pac_p970-userdebug
# HTC One V
add_lunch_combo pac_primoc-userdebug
add_lunch_combo pac_primou-userdebug
# LGE iproj
add_lunch_combo pac_p930-userdebug
add_lunch_combo pac_su640-userdebug
add_lunch_combo pac_vs920-userdebug
# Motorola 2013
add_lunch_combo pac_vanquish-userdebug
add_lunch_combo pac_spyder-userdebug
add_lunch_combo pac_targa-userdebug
add_lunch_combo pac_maserati-userdebug
add_lunch_combo pac_umts_spyder-userdebug
add_lunch_combo pac_solana-userdebug
