#!/bin/bash
#
# ANSI color scheme script for PAC-ROM
# Copyright (C) 2015 The PAC-ROM Project
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Author: MaDc0w
#

echo -e "${rst}${bldred}☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠${rst}"
echo -e "   ${bldred}▄██████▄                                                          ▄██████▄${rst}"
echo -e " ${bldred}▄█${bldwhi}██ ${bldred}██████▄                TO ALL THE XDA NOOBS!                 ▄█${bldwhi}██ ${bldred}██████▄${rst}"
echo -e " ${bldred}██${bldwhi}███${bldred}██${bldwhi}███${bldred}██                  PLEASE READ THIS!                   ██${bldwhi}███${bldred}██${bldwhi}███${bldred}██${rst}"
echo -e " ${bldred}███████ ${bldwhi}██${bldred}██                                                      ${bldred}███████ ${bldwhi}██${bldred}██${rst}"
echo -e " ${bldred}██▀██▀▀██▀██                                                      ██▀██▀▀██▀██${rst}"
echo -e " ${bldred}▀   ▀  ▀   ▀                                                      ▀   ▀  ▀   ▀${rst}"
echo -e "${bldred}☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠${rst}"
echo -e ""
echo -e "     ${bldred}Please remember that this source is currently for private builds ONLY!${rst}"
echo -e "     ${bldred}Public distribution is NOT ALLOWED! All public builds will be removed!${rst}"
echo -e "     ${bldred}It will be welcomed after nightlies (5.0) begin. Thank you,${rst}"
echo -e ""
echo -e "     ${bldcya}The Developers${rst}"
echo -e ""
echo -e "${bldred}☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠${rst}"
echo -e "   ${bldred}▄██████▄                                                          ▄██████▄${rst}"
echo -e " ${bldred}▄█${bldwhi}██ ${bldred}██████▄                TO ALL THE XDA NOOBS!                 ▄█${bldwhi}██ ${bldred}██████▄${rst}"
echo -e " ${bldred}██${bldwhi}███${bldred}██${bldwhi}███${bldred}██                  PLEASE READ THIS!                   ██${bldwhi}███${bldred}██${bldwhi}███${bldred}██${rst}"
echo -e " ${bldred}███████ ${bldwhi}██${bldred}██                                                      ${bldred}███████ ${bldwhi}██${bldred}██${rst}"
echo -e " ${bldred}██▀██▀▀██▀██                                                      ██▀██▀▀██▀██${rst}"
echo -e " ${bldred}▀   ▀  ▀   ▀                                                      ▀   ▀  ▀   ▀${rst}"
echo -e "${bldred}☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠${rst}"
