#!/bin/bash
#
# ANSI color scheme script for PAC-ROM
# Copyright (C) 2015 PAC-Roms Project
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Author: MaDc0w
# Modified by: JoseGalRe
#

echo -e ""
echo -e "   ${bldylw}▄███████▄${rst}          ${ylw}▄▄         ${bldblu}▄██████▄          ${bldred}▄██████▄          ${rst}${mag}▄██████▄  ${rst}"
echo -e " ${bldylw}▄█████████▀▀${rst}       ${ylw}▄▀█▀       ${bldblu}▄██${bldbgwhi}▀████▀${rst}${bldblu}██▄      ${rst}${bldred}▄██${bldbgwhi}▀████▀${rst}${bldred}██▄      ${rst}${mag}▄█${bldwhi}█ █${rst}${mag}██${bldwhi}█ █${rst}${mag}█▄${rst}"
echo -e " ${bldylw}███████▀    ${bldwhi}▄▄  ${bldred}▄██▄${rst}${ylw} █${rst}    ${rst}▄▄  ${bldblu}███${bldbgwhi}▄████${bldbgwhi}▄${rst}${bldblu}███  ${rst}▄▄ ${bldred} ███${bldbgwhi}▄████▄${rst}${bldred}███${rst}  ▄▄  ${rst}${mag}██${bldwhi}███${rst}${mag}██${bldwhi}███${rst}${mag}██${rst}"
echo -e " ${bldylw}███████▄    ${bldwhi}▀▀  ${bldred}▀${bldbgwhi}▄█${rst}${bldred}▀▄██▄  ${rst}▀▀  ${bldblu}██${bldbgwhi}▀▄▄▀▀▄▄▀${rst}${bldblu}██  ${rst}▀▀${bldred}  ██${bldbgwhi}▀▄▄▀▀▄▄▀██${rst}  ▀▀  ${rst}${mag}████████████${rst}"
echo -e " ${bldylw}▀█████████▄▄${bldwhi}        ${bldred}▀${bldbgwhi}▄${rst}${bldred}█▀      ${bldblu}██▀██▀▀██▀██      ${bldred}██▀██▀▀██▀██      ${rst}${mag}██▀██▀▀██▀██${rst}"
echo -e "   ${bldylw}▀███████▀${bldgrn}  www.pac-rom.com  ${bldblu}▀   ▀  ▀   ▀      ${bldred}▀   ▀  ▀   ▀      ${rst}${mag}▀   ▀  ▀   ▀${rst}"
echo -e ""
