#!/bin/bash
#
# ANSI color scheme script for PAC-ROM
# Copyright (C) 2015 The PAC-ROM Project
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Author: MaDc0w
#

echo ""
echo -e "${rst}${blu}${line}${rst}"
echo -e "      ${bldylw}▄███████▄${rst}      ${grn}▄▄▄ ▄                 ${ylw}▄▄          ${bldwhi}▄${rst}             ${grn}▄▄▄${rst}"
echo -e "    ${bldylw}▄█████████▀▀${rst}     ${bldred}▄${bldbggrn}▄▄ ▄██${rst}${bldred}▄${rst}          ${ylw}▄▄▀█▀▀      ${bldred}▄${bldbggrn}▄▄ ${bldwhi}▀${bldgrn} ${bldwhi}▄${bldred}▄${rst}       ${ylw}▄▄${grn}▀${bggrn}█${rst}${grn}▀${ylw}▄${rst}"
echo -e "    ${bldylw}███████▀${rst}        ${bldred}█${bldbgwhi}▀▄███████${rst}     ${bldred}▄▄${bldred}${rst}${ylw}▄▀  ▄▀       ${bldred}${bldbgwhi}█▄█▄█${bldbggrn}▄${bldbgwhi}▀█▀█${rst}    ${ylw}▄████████▄${rst}"
echo -e "    ${bldylw}███████▄${rst}        ${bldred}█${bldbgwhi}▄████████${rst}    ${bldred}█████ ▄${bldred}${rst}${ylw}█${bldred}▄${rst}       ${bldred}▀${bldbgwhi}█▄█▄██▀█${rst}${bldred}▀${rst}    ${ylw}██████████${rst}"
echo -e "    ${bldylw}▀█████████▄▄${rst}    ${bldred}▀████████▀    ${bldred}▀${bldbgwhi}▄${rst}${bldred}██ ██${bldbgylw}▄${rst}${bldred}██       ${bldred}▀${bldbgwhi}▄█▄█▀█${rst}${bldred}▀${rst}     ${ylw}▀████████▀${rst}"
echo -e "      ${bldylw}▀███████▀${rst}      ${bldred}▀██▀▀██▀          ${bldred}▀${bldbgwhi}▄${rst}${bldred}██▀         ${bldred}▀${bldbgwhi}▄█${rst}${bldred}▀${rst}        ${ylw}▀▀████▀▀${rst}"
echo -e "${blu}${line}${rst}"
echo -e "                         ${bldmag}w w w . p a c - r o m . c o m ${rst}"
echo -e "${blu}${line}${rst}"
echo ""
