#!/bin/sh
#
# Squish a CM otapackage for distribution
# cyanogen
#

. ${ANDROID_BUILD_TOP}/vendor/pac/tools/colors

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   OUT_TARGET_HOST=linux-x86
   MD5=md5sum
   XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
   SED=sed
else
   OUT_TARGET_HOST=darwin-x86
   MD5=md5
   XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
   SED=gsed
fi

if [ -z "$OUT" -o ! -d "$OUT" ]; then
	echo "ERROR: $0 only works with a full build environment. $OUT should exist."
	exit 1
fi

if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
    OTAPACKAGE=$OUT/${TARGET_PRODUCT}_debug-ota-$TARGET_BUILD_VARIANT.$USER.zip
elif [ "$TARGET_BUILD_VARIANT" = "userdebug" ]; then
    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
else
    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$USER.zip
fi
if [ ! -f "$OTAPACKAGE" ]; then
	echo "$OTAPACKAGE doesn't exist!";
	exit 1
fi

OPTICHARGER=$ANDROID_BUILD_TOP/vendor/pac/tools/opticharger
QUIET=-q
DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"

REPACK=$OUT/repack.d
printf "${bldcya}Sanitizing environment${txtrst}..."
rm -rf $REPACK
mkdir -p $REPACK
echo


# Unpack the otapackage and opticharge all apks
mkdir $REPACK/ota
(
cd $REPACK/ota
printf "${bldgrn}Unpacking${txtrst}: ${grn}$OTAPACKAGE${txtrst}..."
unzip $QUIET $OTAPACKAGE
echo
cd $REPACK/ota/system/framework
$OPTICHARGER framework-res.apk
cd $REPACK/ota/system/app
find ./ -name \*.apk | $XARGS $OPTICHARGER
)

# Fix build.prop
$SED -i \
	-e '/ro\.kernel\.android\.checkjni/d' \
	-e '/ro\.build\.type/s/eng/user/' \
	$REPACK/ota/system/build.prop

# Delete PAC specific files
if [ -f $ANDROID_BUILD_TOP/vendor/pac/tools/squisher.rm ]; then
	for RM_FILE in `cat $ANDROID_BUILD_TOP/vendor/pac/tools/squisher.rm`; do
		rm -f $REPACK/ota/$RM_FILE
	done
fi

# Delete target product specific files
if [ -f $ANDROID_BUILD_TOP/vendor/pac/tools/$TARGET_PRODUCT-squisher.rm ]; then
	for RM_FILE in `cat $ANDROID_BUILD_TOP/vendor/pac/tools/$TARGET_PRODUCT-squisher.rm`; do
		rm -f $REPACK/ota/$RM_FILE
	done
fi

# Delete unnecessary binaries
( cd $REPACK/ota/system/bin; echo $DELETE_BINS | xargs rm -f; )

# No need for recovery
rm -rf $REPACK/ota/recovery

# Strip modules
[ -d $REPACK/ota/system/lib/modules ] && \
	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded

# Determine what to name the new signed package
if [ -z "$CYANOGEN_NIGHTLY" ]; then
	PACVERSION=`grep 'ro.pacrom.version=' $REPACK/ota/system/build.prop | sed -e 's/ro.pacrom.version=//g'`
	OUTFILE=$OUT/$PACVERSION.zip
	echo; echo "${bldgrn}P${bldppl}A${bldblu}C${bldylw}-VERSION${txtrst}:${cya} $PACVERSION ${txtrst}"; echo
else
	OUTFILE=$OUT/update-squished.zip
fi

# Pack it up and sign
printf "${grn}Zipping package...${txtrst}"
( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
echo
printf "${grn}Signing package...${txtrst}"
SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
java -Xmx1024m \
	-jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
	$REPACK/update.zip $OUTFILE
echo
printf "${grn}Cleaning up...${txtrst}"
rm -rf $REPACK
echo

# Create a md5 checksum image of the repacked package
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`
$MD5 $img >$img.md5sum
echo; echo "${cya}Package complete:${ylw} $OUTFILE ${txtrst}"; echo
echo "${cya}ZIP:${ylw} $img"
echo "${cya}MD5: ${ylw} $MD5"
MD5VAL=`cat $img.md5sum  | awk '{ print $1 }'`
DEVICE=`echo $TARGET_PRODUCT | cut -d "_" -f 2`

echo ${bldylw}
echo "    dMMMMb  .aMMMb  .aMMMb  dMMMMMMMMb .aMMMb  dMMMMb"
echo "   dMP.dMP dMP\"dMP dMP\"VMP dMP\"dMP\"dMPdMP\"dMP dMP dMP"
echo "  dMMMMP\" dMMMMMP dMP     dMP dMP dMPdMMMMMP dMP dMP"
echo " dMP     dMP dMP dMP.aMP dMP dMP dMPdMP dMP dMP dMP"
echo "dMP     dMP dMP  VMMMP\" dMP dMP dMPdMP dMP dMP dMP"
echo
echo "    dMMMMb  .aMMMb  dMMMMMMMMb  .dMMMb"
echo "   dMP.dMP dMP\"dMP dMP\"dMP\"dMP dMP\" VP"
echo "  dMMMMK\" dMP dMP dMP dMP dMP  VMMMb"
echo " dMP\"AMF dMP.aMP dMP dMP dMP dP .dMP"
echo "dMP dMP  VMMMP\" dMP dMP dMP  VMMMP\""
echo ${txtrst}

#OTA link for ease of use !
echo "Use This link in a browser after uploading the the zip to your req'd host."
echo "If you do not know the password ask in the normal places."
echo "${cyarev}                                   LINK                                         ${txtrst}"
echo "http://pac-rom.com/ota/?device=$DEVICE&version=$PACVERSION&md5=$MD5VAL"
echo "${cyarev}                                 END LINK                                       ${txtrst}"
echo "Make sure you use a direct linkable host, got problems"
echo "with the OTA? Contact ${txtbld}pvyParts${txtrst} in hangouts."
echo
)

exit 0
